In [1]:
import numpy as np
import torch

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [5]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [6]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.2497, 0.0845],
        [0.6682, 0.9537]])

In [7]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0848, 0.4659, 0.6473],
        [0.6160, 0.4514, 0.2204]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [17]:
tensor = torch.tensor([
    [  # First 3×3 matrix
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [  # Second 3×3 matrix
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

print(tensor)
print("Shape:", tensor.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
Shape: torch.Size([2, 3, 3])


In [25]:
tensor[:, :, -1]

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [29]:
t1 = torch.cat([
    tensor, tensor
], dim=0)
t1

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [35]:
# Tensor A: shape (2, 3, 3)
A = torch.tensor([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
], dtype=torch.float32)

# Tensor B: shape (2, 3, 3)
B = torch.tensor([
    [[1, 0, 0],
     [0, 1, 0],
     [0, 0, 1]],
    
    [[2, 0, 0],
     [0, 2, 0],
     [0, 0, 2]]
], dtype=torch.float32)


In [37]:
result = torch.bmm(A, B)

In [38]:
print(result)
print(result.shape)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[20., 22., 24.],
         [26., 28., 30.],
         [32., 34., 36.]]])
torch.Size([2, 3, 3])


In [45]:
A = torch.rand(5, 3, 2)
B = torch.rand(1, 2, 4)
C = A @ B  

In [46]:
C.shape

torch.Size([5, 3, 4])

In [47]:
tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
tensor.add_(5)

tensor([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [50]:
tensor + tensor

tensor([[12, 14, 16],
        [18, 20, 22],
        [24, 26, 28]])