In [2]:
import torch

In [4]:
if torch.cuda.is_available():
    device = torch.get_default_device()
    print(f"Using device: {device}")
else:
    device = torch.device("cpu")
    print("CUDA is not available, using CPU")


CUDA is not available, using CPU


### Creating Tensors

In [ ]:
# using empty
x = torch.empty(3, 4) # the values are uninitialized, so they can be anything
print(x)

tensor([[1.5766e-19, 1.0256e-08, 4.1019e-08, 3.1473e+12],
        [4.3359e-08, 1.0374e-08, 6.6015e-07, 1.2680e+16],
        [2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31]])


In [6]:
type(x) # the type of the tensor

torch.Tensor

In [7]:
a = torch.ones(3, 4) # creates a tensor filled with ones
print(a)
b = torch.zeros(3, 4) # creates a tensor filled with zeros
print(b)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [8]:
#using rand
c = torch.rand(3, 4) # creates a tensor with random values
print(c)

tensor([[0.2264, 0.5540, 0.3990, 0.5102],
        [0.4982, 0.8107, 0.0865, 0.2376],
        [0.3594, 0.6649, 0.1687, 0.6889]])


In [9]:
torch.manual_seed(0) # set the random seed for reproducibility
d = torch.rand(3, 4) # creates a tensor with random values
print(d)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])


In [10]:
# using arange
e = torch.arange(0, 10, 2) # creates a tensor with values from 0 to 10 with step size 2
print(e)

tensor([0, 2, 4, 6, 8])


In [11]:
# using linspace
f = torch.linspace(0, 1, 5) # creates a tensor with 5 values evenly spaced between 0 and 1
print(f)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [12]:
# using eye
g = torch.eye(3) # creates a 3x3 identity matrix
print(g)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [13]:
# using full
h = torch.full((3, 4), 7) # creates a tensor filled with the value 7
print(h)

tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]])


### Tensor Shapes

In [14]:
tensor = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32) # creates a tensor with specific values and type

In [15]:
tensor.shape # returns the shape of the tensor

torch.Size([2, 2])

In [21]:
# empty_like, ones_like, zeros_like
# creates a tensor with the same shape as another tensor
# this is useful when you want to create a tensor with the same shape as an existing tensor

x = torch.empty_like(tensor) # creates an empty tensor with the same shape as tensor
print(x)
y = torch.ones_like(tensor) # creates a tensor filled with ones with the same shape as tensor
print(y)
z = torch.zeros_like(tensor) # creates a tensor filled with zeros with the same shape as tensor
print(z)
i = torch.rand_like(tensor) # creates a tensor with random values with the same shape as tensor
print(i)

tensor([[5.7937e-315,  0.0000e+00],
        [5.7921e-315, 5.7843e-315]], dtype=torch.float64)
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[0.1786, 0.3511],
        [0.5813, 0.2882]], dtype=torch.float64)


### Tensor Data Types

In [18]:
x.dtype # returns the type of the tensor

torch.float32

In [19]:
# torch.set_default_dtype(torch.float64) # set the default type for tensors to float64

torch.tensor([
    [1.234, 2.34],
    [3.456, 4.567]
], dtype=torch.float64 # creates a tensor with specific values and type
)

tensor([[1.2340, 2.3400],
        [3.4560, 4.5670]], dtype=torch.float64)

In [20]:
#using to()
# converts the tensor to a different type
tensor = tensor.to(torch.float64) # converts the tensor to float64
print(tensor)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


### Mathematical Operations

In [22]:
x = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32) # creates a tensor with specific values and type
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [24]:
# addition, subtraction, multiplication, division, int_division, modulus, exponentiation
print(x + 2) # adds 2 to each element of the tensor
print(x - 2) # subtracts 2 from each element of the tensor
print(x * 2) # multiplies each element of the tensor by 2
print(x / 2) # divides each element of the tensor by 2
print(x // 2) # integer division of each element of the tensor by 2
print(x % 2) # modulus of each element of the tensor by 2
print(x ** 2) # exponentiation of each element of the tensor by 2
print(torch.clamp(x, 2, 3)) # clamps the values of the tensor between 2 and 3

# using in-place operations
x.add_(2) # adds 2 to each element of the tensor in-place
print(x)
x.sub_(2) # subtracts 2 from each element of the tensor in-place
print(x)
x.mul_(2) # multiplies each element of the tensor by 2 in-place
print(x)
x.div_(2) # divides each element of the tensor by 2 in-place
print(x)
x.int() # converts the tensor to int
print(x)

# using item()
# converts a single-element tensor to a Python number
x = torch.tensor(3.14)
print(x.item()) # prints 3.14

tensor(5.1400)
tensor(1.1400)
tensor(6.2800)
tensor(1.5700)
tensor(1.)
tensor(1.1400)
tensor(9.8596)
tensor(3.)
tensor(5.1400)
tensor(3.1400)
tensor(6.2800)
tensor(3.1400)
tensor(3.1400)
3.140000104904175


### Reduction Operations

In [34]:
tensor = torch.randint(size=(3, 4), low=0, high=10, dtype=torch.float64) # creates a tensor with random integer values

In [35]:
tensor

tensor([[3., 0., 5., 5.],
        [2., 9., 1., 8.],
        [8., 3., 6., 9.]], dtype=torch.float64)

In [36]:
#summing
#sum of all elements
print(tensor.sum()) # prints the sum of all elements of the tensor
#sum of each column
print(tensor.sum(dim=0)) # prints the sum of each column of the tensor
#sum of each row
print(tensor.sum(dim=1)) # prints the sum of each row of the tensor
#sum of each element
print(tensor.sum(dim=-1)) # prints the sum of each element of the tensor
print(tensor.sum(dim=0, keepdim=True)) # prints the sum of each element of the tensor with keepdim=True
print(tensor.sum(dim=1, keepdim=True)) # prints the sum of each element of the tensor with keepdim=True
print(tensor.sum(dim=-1, keepdim=True)) # prints the sum of each element of the tensor with keepdim=True
print(tensor.sum(dim=0, keepdim=False)) # prints the sum of each element of the tensor with keepdim=False
print(tensor.sum(dim=1, keepdim=False)) # prints the sum of each element of the tensor with keepdim=False
print(tensor.sum(dim=-1, keepdim=False)) # prints the sum of each element of the tensor with keepdim=False
print(tensor.sum(dim=0, keepdim=True)) # prints the sum of each element of the tensor with keepdim=True
print(tensor.sum(dim=1, keepdim=True)) # prints the sum of each element of the tensor with keepdim=True


tensor(59., dtype=torch.float64)
tensor([13., 12., 12., 22.], dtype=torch.float64)
tensor([13., 20., 26.], dtype=torch.float64)
tensor([13., 20., 26.], dtype=torch.float64)
tensor([[13., 12., 12., 22.]], dtype=torch.float64)
tensor([[13.],
        [20.],
        [26.]], dtype=torch.float64)
tensor([[13.],
        [20.],
        [26.]], dtype=torch.float64)
tensor([13., 12., 12., 22.], dtype=torch.float64)
tensor([13., 20., 26.], dtype=torch.float64)
tensor([13., 20., 26.], dtype=torch.float64)
tensor([[13., 12., 12., 22.]], dtype=torch.float64)
tensor([[13.],
        [20.],
        [26.]], dtype=torch.float64)


In [37]:
# Mean
# mean of all elements
print(tensor.mean()) # prints the mean of all elements of the tensor

tensor(4.9167, dtype=torch.float64)


In [38]:
# max, min
# max of all elements
print(tensor.max()) # prints the max of all elements of the tensor
print(tensor.min()) # prints the min of all elements of the tensor

tensor(9., dtype=torch.float64)
tensor(0., dtype=torch.float64)


In [39]:
# argmax, argmin
# index of max of all elements
print(tensor.argmax()) # prints the index of the max of all elements of the tensor
print(tensor.argmin()) # prints the index of the min of all elements of the tensor

tensor(5)
tensor(1)


In [40]:
mat_1 = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32) # creates a tensor with specific values and type
mat_2 = torch.tensor([
    [5, 6],
    [7, 8]
], dtype=torch.float32) # creates a tensor with specific values and type

In [41]:
mat_1@mat_2 # matrix multiplication
mat_1.matmul(mat_2) # matrix multiplication

tensor([[19., 22.],
        [43., 50.]])

In [49]:
r = torch.rand(3, 4) # creates a tensor with random values
print(r)

tensor([[0.5932, 0.1123, 0.1535, 0.2417],
        [0.7262, 0.7011, 0.2038, 0.6511],
        [0.7745, 0.4369, 0.5191, 0.6159]])


In [50]:
r.T # transpose of the tensor

tensor([[0.5932, 0.7262, 0.7745],
        [0.1123, 0.7011, 0.4369],
        [0.1535, 0.2038, 0.5191],
        [0.2417, 0.6511, 0.6159]])

In [52]:
x = torch.rand(2, 4) # creates a tensor with random values

In [54]:
x

tensor([[0.8102, 0.9801, 0.1147, 0.3168],
        [0.6965, 0.9143, 0.9351, 0.9412]])

In [56]:
torch.transpose(x, 0, 1) # transpose of the tensor
# torch.transpose(x, 1, 0) # transpose of the tensor

tensor([[0.8102, 0.6965],
        [0.9801, 0.9143],
        [0.1147, 0.9351],
        [0.3168, 0.9412]])

### Comparision Opearations

In [57]:
x = torch.randint(size=(3, 4), low=0, high=10, dtype=torch.float64) # creates a tensor with random integer values
print(x)
y = torch.randint(size=(3, 4), low=0, high=10, dtype=torch.float64) # creates a tensor with random integer values
print(y)

tensor([[9., 6., 1., 0.],
        [2., 9., 4., 3.],
        [9., 3., 9., 3.]], dtype=torch.float64)
tensor([[9., 8., 5., 3.],
        [2., 8., 5., 6.],
        [6., 5., 7., 2.]], dtype=torch.float64)


In [58]:
# greater than, less than, greater than or equal to, less than or equal to
print(x > y) # prints True if x is greater than y
print(x < y) # prints True if x is less than y
print(x >= y) # prints True if x is greater than or equal to y
print(x <= y) # prints True if x is less than or equal to y
print(x == y) # prints True if x is equal to y
print(x != y) # prints True if x is not equal to y
print(x.eq(y)) # prints True if x is equal to y
print(x.ne(y)) # prints True if x is not equal to y
print(x.gt(y)) # prints True if x is greater than y
print(x.lt(y)) # prints True if x is less than y
print(x.ge(y)) # prints True if x is greater than or equal to y
print(x.le(y)) # prints True if x is less than or equal to y

tensor([[False, False, False, False],
        [False,  True, False, False],
        [ True, False,  True,  True]])
tensor([[False,  True,  True,  True],
        [False, False,  True,  True],
        [False,  True, False, False]])
tensor([[ True, False, False, False],
        [ True,  True, False, False],
        [ True, False,  True,  True]])
tensor([[ True,  True,  True,  True],
        [ True, False,  True,  True],
        [False,  True, False, False]])
tensor([[ True, False, False, False],
        [ True, False, False, False],
        [False, False, False, False]])
tensor([[False,  True,  True,  True],
        [False,  True,  True,  True],
        [ True,  True,  True,  True]])
tensor([[ True, False, False, False],
        [ True, False, False, False],
        [False, False, False, False]])
tensor([[False,  True,  True,  True],
        [False,  True,  True,  True],
        [ True,  True,  True,  True]])
tensor([[False, False, False, False],
        [False,  True, False, False],
    

In [61]:
# log, exp, sqrt, abs, sigmoid, tanh, relu
print(torch.log(x)) # prints the natural logarithm of x
print(torch.exp(x)) # prints the exponential of x
print(torch.sqrt(x)) # prints the square root of x
print(torch.abs(x)) # prints the absolute value of x
print(torch.sigmoid(x)) # prints the sigmoid of x
print(torch.tanh(x)) # prints the hyperbolic tangent of x
print(torch.relu(x)) # prints the rectified linear unit of x
print(torch.softmax(x, dim=0)) # prints the softmax of x along dimension 0
print(torch.softmax(x, dim=1)) # prints the softmax of x along dimension 1
print(torch.softmax(x, dim=-1)) # prints the softmax of x along the last dimension

tensor([[2.1972, 1.7918, 0.0000,   -inf],
        [0.6931, 2.1972, 1.3863, 1.0986],
        [2.1972, 1.0986, 2.1972, 1.0986]], dtype=torch.float64)
tensor([[8.1031e+03, 4.0343e+02, 2.7183e+00, 1.0000e+00],
        [7.3891e+00, 8.1031e+03, 5.4598e+01, 2.0086e+01],
        [8.1031e+03, 2.0086e+01, 8.1031e+03, 2.0086e+01]], dtype=torch.float64)
tensor([[3.0000, 2.4495, 1.0000, 0.0000],
        [1.4142, 3.0000, 2.0000, 1.7321],
        [3.0000, 1.7321, 3.0000, 1.7321]], dtype=torch.float64)
tensor([[9., 6., 1., 0.],
        [2., 9., 4., 3.],
        [9., 3., 9., 3.]], dtype=torch.float64)
tensor([[0.9999, 0.9975, 0.7311, 0.5000],
        [0.8808, 0.9999, 0.9820, 0.9526],
        [0.9999, 0.9526, 0.9999, 0.9526]], dtype=torch.float64)
tensor([[1.0000, 1.0000, 0.7616, 0.0000],
        [0.9640, 1.0000, 0.9993, 0.9951],
        [1.0000, 0.9951, 1.0000, 0.9951]], dtype=torch.float64)
tensor([[9., 6., 1., 0.],
        [2., 9., 4., 3.],
        [9., 3., 9., 3.]], dtype=torch.float64)
tensor([[4.9

### Reshaping Tensors

In [63]:
a = torch.ones(4, 4) # creates a tensor filled with ones
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [68]:
a.reshape(2, 8) # reshapes the tensor to 2x8
a.reshape(8, 2) # reshapes the tensor to 8x2
a.reshape(4, 4) # reshapes the tensor to 4x4
a.reshape(2, 2, 2, 2) # reshapes the tensor to 2x2x2x2

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [71]:
# flatten
a.flatten() # flattens the tensor to 1D
a.flatten(start_dim=0) # flattens the tensor to 1D
a.flatten(start_dim=1) # flattens the tensor to 1D

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [72]:
ran_1 = torch.rand(2, 3, 4)
ran_1

tensor([[[0.9704, 0.8369, 0.2820, 0.3742],
         [0.0237, 0.4910, 0.1235, 0.1143],
         [0.4725, 0.5751, 0.2952, 0.7967]],

        [[0.1957, 0.9537, 0.8426, 0.0784],
         [0.3756, 0.5226, 0.5730, 0.6186],
         [0.6962, 0.5300, 0.2560, 0.7366]]])

In [73]:
ran_1.permute(2, 0, 1)

tensor([[[0.9704, 0.0237, 0.4725],
         [0.1957, 0.3756, 0.6962]],

        [[0.8369, 0.4910, 0.5751],
         [0.9537, 0.5226, 0.5300]],

        [[0.2820, 0.1235, 0.2952],
         [0.8426, 0.5730, 0.2560]],

        [[0.3742, 0.1143, 0.7967],
         [0.0784, 0.6186, 0.7366]]])

In [77]:
#unsqueeze
c = torch.rand(256, 256, 3)
# print(c)
print(c.unsqueeze(0).shape) # adds a new dimension at index 0
print(c.unsqueeze(1).shape) # adds a new dimension at index 1
print(c.unsqueeze(2).shape) # adds a new dimension at index 2

torch.Size([1, 256, 256, 3])
torch.Size([256, 1, 256, 3])
torch.Size([256, 256, 1, 3])


In [83]:
# sequzze
d = torch.rand(1, 2)
print(d.squeeze(0).shape) # removes the dimension at index 0

torch.Size([2])
